version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: udagram-reverseproxy
  backend_user:
    build:
      context: ./udagram-api/udagram-user-service
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api/udagram-feed-service
    image: udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend