version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker images
          command: |
            docker-compose -f docker-compose-build.yaml build --parallel
      - run:
          name: Tag Docker images
          command: |
            docker tag udagram-api-user golf4sp/udagram-api-user:v2
            docker tag udagram-api-feed golf4sp/udagram-api-feed:v2
            docker tag udagram-reverseproxy golf4sp/udagram-reverseproxy:v2
            docker tag udagram-frontend golf4sp/udagram-frontend:v2
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push golf4sp/udagram-api-user:v2
            docker push golf4sp/udagram-api-feed:v2
            docker push golf4sp/udagram-reverseproxy:v2
            docker push golf4sp/udagram-frontend:v2
workflows:
  version: 2
  build-main:
    jobs:
      - build:
          filters:
            branches:
              only: main