apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: udagram
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      service: frontend
  template:
    metadata:
      labels:
        app: frontend
        service: frontend
    spec:
      containers:
      - name: frontend
        image: golf4sp/udagram-frontend:v2
        ports:
        - containerPort: 80