apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api-deployment
  labels:
    app: udagram
    service: feed-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      service: feed-api
  template:
    metadata:
      labels:
        app: udagram
        service: feed-api
    spec:
      containers:
      - name: udagram-api-feed
        image: golf4sp/udagram-api-feed:v2
        envFrom:
          - secretRef:
              name: env-secret
        ports:
        - containerPort: 8080