apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-deployment
  labels:
    app: udagram
    service: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      service: user-api
  template:
    metadata:
      labels:
        app: udagram
        service: user-api
    spec:
      containers:
      - name: udagram-api-user
        image: golf4sp/udagram-api-user:v2
        envFrom:
          - secretRef:
              name: env-secret
        ports:
        - containerPort: 8080