apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: udagram
    service: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
      service: reverseproxy
  template:
    metadata:
      labels:
        app: udagram
        service: reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: golf4sp/udagram-reverseproxy:v2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80